### ISSUE TITLE
Handler server side extractor error

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/CONSORT-frontend#26]
Show an error if there is errors on the server side. For example if we upload a file with undexpected text in it (I just used a LICENSE file) the server will be done but with a `"StatusMessage.error: list index out of range"` message. Can we parse the message and show an error? Right now the "processing..." spinner just keeps spinning.

**Comment by minump** [comment]
<img width="1046" alt="Screenshot 2023-05-12 at 3 06 44 PM" src="https://github.com/clowder-framework/CONSORT-frontend/assets/22112888/8407e8fd-6323-4c0a-a752-2b033ec04450">

Display extractor status messages in overlay
